spring.application.name=VIA Tabloid
spring.datasource.url=jdbc:postgresql://localhost:5432/viatab
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

